spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

logging.level.root=WARN
logging.level.com.aditya.expensetracker.expense_tracker=INFO

spring.jpa.show-sql=false

app.rate-limit.email-action.capacity=3
app.rate-limit.email-action.period=1h