spring.application.name=expense-tracker

SPRING.DATASOURCE.URL=${DB_URL}
SPRING.DATASOURCE.USERNAME=${DB_USERNAME}
SPRING.DATASOURCE.PASSWORD=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect