spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

logging.level.root=WARN
logging.level.com.aditya.expensetracker.expense_tracker=INFO

spring.jpa.show-sql=false

app.rate-limit.email-action.capacity=3
app.rate-limit.email-action.period=1h
app.rate-limit.upload.capacity=10
app.rate-limit.upload.period=1m

app.rate-limit.analytics.capacity=30
app.rate-limit.analytics.period=1m
