spring.application.name=expense-tracker
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
app.refresh-token.expiration-days=${REFRESH_TOKEN_EDATE}
app.jwt.expiration-ms=${ACCESS_TOKEN_EMS}
app.email-verification.expiration-hours=${VERIFICATION_TOKEN_EHR}
app.password-reset.expiration-hours=${PASSWORD_RESET_TOKEN_EHR}
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.contact.email=${APP_CONTACT_EMAIL}

aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_BUCKET_NAME}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.cache.redis.time-to-live=10m

spring.cache.redis.cache-null-values=false

spring.cache.redis.key-prefix=expense-tracker::

spring.cache.redis.use-key-prefix=true

app.rate-limit.trusted-proxies=

management.server.port=8081

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

management.endpoint.health.group.readiness.include=readinessState,db,redis,s3

management.health.mail.enabled=false