SPRING.DATASOURCE.URL=${DB_URL}
SPRING.DATASOURCE.USERNAME=${DB_USERNAME}
SPRING.DATASOURCE.PASSWORD=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


logging.level.root=INFO
logging.level.com.aditya.expensetracker.expense_tracker=DEBUG

app.rate-limit.auth.capacity=20
app.rate-limit.auth.period=1m

app.rate-limit.email-action.capacity=20
app.rate-limit.email-action.period=1m

app.rate-limit.api.capacity=100
app.rate-limit.api.period=1m
app.rate-limit.upload.capacity=20
app.rate-limit.upload.period=1m

app.rate-limit.analytics.capacity=60
app.rate-limit.analytics.period=1m
